// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkbbddrbhaufeyhkpnzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrYmJkZHJiaGF1ZmV5aGtwbnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODYyMzUsImV4cCI6MjA2Njc2MjIzNX0.BHJJe_Dnh-IJWIxVDCz6A7_TKKGOG9-6HfBcO-3XaOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);